### ISSUE TITLE
Either support ES6 modules (.mjs) or provide a pre-built ES5 version

### ISSUE THREAD

**Issue by n1474335** [nf404/crypto-api#9]
It's currently not possible to use crypto-api in node without running it through a packer like webpack or a transpiler like babel.

It should be possible to import crypto-api into a node script. To support ES6 modules, the source files should use `.mjs` extensions instead of `.js`. This would allow it to be imported using ES6 `import` syntax and then run using `node --experimental-modules`.

Alternatively, could a pre-built ES5 version be packaged up in the npm release? I've tried running the included webpack script as a postinstall action, but the resulting library doesn't actually export anything.

**Comment by nf404** [comment]
thx for such idea. I will check how this work and apply changes

**Comment by n1474335** [comment]
If anyone else if having this problem, I'm currently solving it by using this: https://www.npmjs.com/package/js-to-mjs

```
npm install js-to-mjs --save-dev
```
Then add the following to the scripts section of package.json
```
"postinstall": "npx j2m node_modules/crypto-api/src/crypto-api.js"
```

This replaces all crypto-api file extensions with `.mjs`. You then have to import the library like this:

```
import CryptoApi from "crypto-api/src/crypto-api";
```

**Comment by n1474335** [comment]
Thanks for fixing this, my build is a lot cleaner now!
